version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - symfony

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:

volumes:
  db_data:
